### ISSUE TITLE
[META-ISSUE] TCAS implementation

### ISSUE THREAD

**Issue by lukecologne** [flybywiresim/a32nx#1097]
I'm currently working on TCAS, but currently taking a bit of a break (2 days) because of an exam coming up

**Features to implement:**
- [x]  proper traffic display logic (above, below etc.)
- [x]  proper display on the ND (vertical speed, relative alt)
- [x]  Traffic threat assesment (proximate/TA/RA)
- [ ]  Messages on ND (for ex. TA only, change range/change mode) 
- [ ]  Compatability with #934 (seperate PFD/NDs)
- [ ]  Integration with GPWS (reduce sensitvity level to 2 when GPWS warning active)
- [ ]  RA generation
  - [ ] display RA instructions on PFD
- [ ]  Aural warnings
- [ ] AutoTCAS maybe? (would depend on RA generation)

**References**

* https://www.faa.gov/documentlibrary/media/advisory_circular/tcas%20ii%20v7.1%20intro%20booklet.pdf
  (Very extensive, also talks about RA generation)

* ![grafik](https://user-images.githubusercontent.com/39596827/95025534-af3a0200-068a-11eb-8e07-f31b925f0599.png)

* ![grafik](https://user-images.githubusercontent.com/39596827/95025549-d264b180-068a-11eb-8e44-96cfa6aeb58d.png)

* ![grafik](https://user-images.githubusercontent.com/39596827/95025572-017b2300-068b-11eb-9365-480247347d71.png)

**Comment by Benjozork** [comment]
cc. @Pleasure0102, you are working on the new DRAIMS so might wanna sync up to make sure it's integrated easily in the future

**Comment by Pleasure0102** [comment]
i think honestly it is a bit early, but once we get stuff ingame, i think then is the time to get synced :)

**Comment by Khitiara** [comment]
https://gist.github.com/Khitiara/62b8e518eb22f2063edb6983b2fbec08 skeleton of tcas data fetching using rust, im not sure how to integrate with existing code and cant test it myself anyway
