### ISSUE TITLE
Hard Fork A32NX

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#1215]
# The Problem

Our mod replaces the vanilla A320neo in the game, making it more difficult for users to switch back and forth.

MSFS updates can, and usually do, break our mod, because the mod is still dependent on some vanilla files that we do not have in our repo.

# Solution

Copy all files needed into our repo, and rename them.

# Execution

- [ ] Port base aircraft SimObject files (PR #2079)
- [ ] Port base aircraft avionics files
- [ ] Move all files to new VFS directory

# Pros

- Easily switch between vanilla and modded aircraft
- Less chance of MSFS updates breaking the mod
- More freedom over how we structure our mod

# Cons

- This might make it more difficult to absorb asobo's updates into our mod.

# Notes

We haven't decided yet whether we will do this or not.

**Comment by Benjozork** [comment]
> This might make it more difficult to absorb asobo's updates into our mod.

I don't think this would even be a problem if we hard fork. The reason we update the files according to their changes is because their changes might break stuff, rarely because they fixed something we couldn't fix. When that's the case, the fix is in native code. If they do fix something we didn't fix, then we can very easily fix it ourselves anyway without including their changes specifically.

Furthermore, at the point we are at, merging in the changes that are not needed for compatibility with the base A320 will be more and more complicated and time-consuming for little benefit.

**Comment by davidwalschots** [comment]
> More freedom over how we structure our mod

I'm assuming this relates to the code structure? If so, I'd definitely go for a hard fork.

Looking at the current code base we can see a mishmash of coding styles, different levels of abstractions, and sometimes a lack of abstractions in general. We have been driven in this direction by Asobo's code which itself was created under considerable pressure. That's very understandable, but will bite us at some point. Proper software design should make it easier to work with the code base, relate certain code to A320 manuals (i.e. find the source of information), and make things unit testable. I recently mentioned on Discord that I'd like to make the code unit testable, but I don't really think anyone feels like mocking all the SimVar inputs for a function which spans hundreds of lines. I have lots on ideas on how to make that easier, but need to know if we are "allowed" to move away from the Asobo structure.

**Question**: what additional information do we need to uncover, and/or what questions do we need to answer before a decision can be made on hard forking or not?

**Comment by Clink1234** [comment]
I want to note on this issue a more extensive writeup of the problem and possible solutions. It was closed as duplicate but is a much better issue than this one. https://github.com/flybywiresim/a32nx/issues/3272
