### ISSUE TITLE
[META] standby instrument (ISIS)

### ISSUE THREAD

**Issue by 2hwk** [flybywiresim/a32nx#1233]
**Is your feature request related to a problem? Please describe.**

Someperson#4953 keeps dming me ISIS material on discord, please help. 

**Describe the feature you'd like to see implemented**

# ELECTRIC

## Description 

![logic](https://cdn.discordapp.com/attachments/759633355083219005/764322413168558080/unknown.png)

Currently ISIS Indicator will switch off even in flight if the batteries and all other main electric systems are switched off. This is incorrect, as the ISIS indicator draws power from both the dc ess bus which supplies critical systems as well as a hot bus (which constantly supplies power until the batteries are entirely drained). The power supply from the hot bus is only active if the calibrated air speed is above 50 knots. 

## Checks 

- [ ] ISIS ELEC
  - [ ] Correct implementation of Standby Instrument Power System (Partially Implemented)
  - [x] Should check if calculated air speed is >50 knots, and keep the instrument ON even if battery is off as long as emergency power is avail.
    - ``(if (cas > 50 knots) AND HOT BUS ON ) OR DC ESS BUS ON``
  - [ ] Display does not immediately power off, delay of 50-200ms where the display will stay on if power is supplied in that interval. (Partially Implemented)

Transparency time for the ISIS indicator is between 50ms - 200 ms. Display is lost during power supply cut off if power is not supplied in this time.
 
# SYSTEMS

## Description

**A. System Performance**

The parameter computation frequency is sufficient to respect the required performances and to avoid important gap between two consecutive displayed values. The elasped time between the acquisition of air data and the display of parameters is less than 200 ms. 

_(1) Standby airspeed indicator function_

The ISIS indicator can operate from 0 to 600 knots without deterioration.

_(2) Standby altimeter function_

The ISIS indicator can operate from -2500 to 55,000 ft and at 40,000 ft/min speed variation without deterioration

_(3) Standby horizon function_

The ISIS indicator can operate from -180 deg to +180 deg. in pitch and roll without deterioration.

- Gyrometers (3): the indicator can follow a 100 deg./s pitch or roll variation, a 10,000 deg./square second angular acceleration. The associated monitoring is triggered when angular speeds become higher than 100 deg./s

- Accelerometers (2): The aassociated monitoring is triggered when the constant acceleration in the x and/or y axis becomes greater than 2.5g. If this monitoring is triggered, the "WAIT ATT" message is displayed.

If the condition becomes normal again and if the attitude monitoring is triggered when the constant acceleration in x and/or y axis becomes greater than 2.5g. If this monitoring is triggered, the "WAIT ATT" message is displayed.

If the condition becomes normal again and if the attitude performance remains adequete for 10 seconds, the "WAIT ATT" message disappears and is replaced by the horizon display.

Otherwise, after 10 seconds or if the attitude performance is affected, the attitude function is considered as failed and the "ATT:RST" message is displayed in place of the "WATT ATT" message (Ref. Fig. 023)

Pressing the RST pushbutton switch more than 2 seconds in steady flight quickly resets the attitude information.

## Checks 

- [ ] ATT RESET - Correct current incorrect behaviour
   - [ ] 2 second push and hold instead of push
- [ ] Will start to lose calibration if plane goes well outside of stated envelope.
- [ ] WAIT ATT
   - [ ] Correctly formatted message box
   - [ ] Pauses display refresh when triggered
   - [ ] If attitude performance goes out of spec for 10 seconds, failure occurs (ATT:RESET)
- [ ] ATT:RESET
    - [ ] Correctly formatted message box
    - [ ] Blacks out display?
    - [ ] Requires use of ATT RESET push button (press and hold 2 seconds)

**References**

https://www.pprune.org/showthread.php?p=6817862
Someperson#4953 on discord

**Additional context**

Discord username (if different from GitHub):

**Comment by lukecologne** [comment]
Reopening as wished in #1261

**Comment by davidwalschots** [comment]
This meta issue has the following item checked:
> Should check if calculated air speed is >50 knots, and keep the instrument ON even if battery is off as long as emergency power is avail

#1261 attempted to implement this. It assumed the default ELEC system was good enough to do so. The default ELEC system has issues which are now solved with a new ELEC implementation. Thus #3980 will improve on the implementation. Note that I'm not using CAS (do you mean calibrated airspeed instead of calculated airspeed?) but IAS at the moment. I'm not yet aware of CAS being available/calculated anywhere.

Note that I'm not making any attempt to implement:
> Display does not immediately power off, delay of 50-200ms where the display will stay on if power is supplied in that interval.

**Comment by tracernz** [comment]
In progess #5190

**Comment by 2hwk** [comment]
Reopening as not everything in this meta issue has been addressed.
