### ISSUE TITLE
[BUG] Meta issue for wrong textures and push buttons in the cockpit

### ISSUE THREAD

**Issue by komp1821** [flybywiresim/a32nx#1410]
### INTRO

**UPDATED 15-NOV-2020**

I took some time and compared the entire cockpit of the simulator with the real one. I'm using this issue to keep track of all the differences and inaccuracies of the Asobo model. I'm going to make a checkbox item for every issue I come across. Also feel free to remind me of anything that's missing.

I will take more and detailed pictures whenever possible. If you have high quality pictures and want to share them with me, hit me up.

**I _do know_ that our modelers and designers are not able to fix most of this for the time being. But it will come in handy once they are.**

Discord name: komp#1821

### REFERENCES
To start off with, I made this tiny PDF with comparison pictures of the overhead and center pedestal. Im going to continue it this way with the other facilities in the cockpit. This issue will receive regular updates.

[a32nx panel comparison.pdf](https://github.com/flybywiresim/a32nx/files/5393623/a32nx.panel.comparison.pdf)

_____________
_____________

### KNOWN ISSUES

**ADIRS panel**
- [ ] **_ADIRS panel:_** ON BAT annunciator light should light up during light test
- [x] **_ADIRS panel:_** IR pushbuttons don’t have ALIGN indication IRL
- [ ] **_ADIRS panel:_** ATT label of IR2 is covered by lightplate screw
_____________________
**EVAC&EMER ELEC PWR panel**
- [ ] **_EVAC&EMER ELEC PWR panel:_** EVAC COMMAND push button legends should be red EVAC and white ON
- [ ] **_EVAC&EMER ELEC PWR panel:_** (not visible) EMER GEN TEST pushbutton: below the cap should be the same type as the (round) call pushbuttons, not a Korry 
- [ ] **_EVAC&EMER ELEC PWR panel:_** (not visible) RAT MAN ON pushbutton: below the cap should be the same type as the (round) call pushbuttons, not a Korry
- [ ] **_EVAC&EMER ELEC PWR panel:_** SMOKE legend in GEN 1 LINE pushbutton should be amber, not red
- [ ] **_EVAC&EMER ELEC PWR panel:_** RAT & EMER GEN annunciator (not a pushbutton): FAULT legend should be red. Blue dots should not light up
_____________________
**GPWS panel**
- [ ] **_GPWS panel:_** LDG PLAP 3 pushbutton should have an ON legend rather than an OFF legend
_____________________
**OXYGEN & CALLS panel**
- [ ] **_OXYGEN & CALLS panel:_** Passenger oxygen system annunciator (not a pushbutton!) should be white
- [ ] **_OXYGEN & CALLS panel:_** (not visible) MASK MAN ON pushbutton below the cap should be the same type as the (round) call pushbuttons, not a Korry
- [ ] **_OXYGEN & CALLS panel:_** EMER call pushbutton should have an amber CALL legend rather than a blue ON
- [ ] **_OXYGEN & CALLS panel:_** WIPER label should be the same size as RAIN RPLNT
- [x] **_OXYGEN & CALLS panel:_** Position marks of the wiper switch scale should be bold
- **_OXYGEN & CALLS panel:_** _NOTE: the ALL CALL push button is optional. Most NEOs don’t have it_
_____________________
**PRESS & INT LT panel**
- [ ] **_PRESS & INT LT panel:_** CABIN PRESS title should be bigger 
- [ ] **_PRESS & INT LT panel:_** INT LT title should be bigger
- [ ] **_PRESS & INT LT panel:_** SIGNS title should be bigger
- [ ] **_PRESS & INT LT panel:_** MODE SEL pushbutton: MAN legend should be white
- [ ] **_PRESS & INT LT panel:_** Scale of LDG ELEV selector is messed up. Compare the pictures
- [ ] **_PRESS & INT LT panel:_** Ditching pushbutton should light up during light test 
- [x] **_PRESS & INT LT panel:_** Typo: COMPAS is missing an ‘S’
- [ ] **_PRESS & INT LT panel:_** ANN LT switch: TEST/DIM legends too far apart
- **_PRESS & INT LT panel:_** _NOTE: SEAT BELTS switch AUTO function is optional_ 
- [ ] **_PRESS & INT LT panel:_** EMER EXIT LT annunciator legend should be amber OFF and not boxed
_____________________
**AIR COND panel**
- [x] **_AIR COND panel:_** Position marks of the PACK FLOW selector scale should be bold
- [ ] **_AIR COND panel:_** RAM AIR pushbutton has no emissive texture during light test
- **_AIR COND panel:_** _NOTE: HEATER CAPT and HEATER F/O switches in the IRL picture are optional. If not installed, the lines left and right of the COCKPIT box are not present_
- [ ] **_AIR COND panel:_** There should be a small green line leading to the temperature selectors
_____________________
**ELEC panel**
- [ ] **_ELEC panel:_** COMMERCIAL pushbutton should not have a FAULT legend 
- [ ] **_ELEC panel:_**  Battery voltage displays are too wide
- [ ] **_ELEC panel:_**  AC ESS FEED pushbutton legend should be ALTN legend rather than OFF
_____________________
**HYD/FUEL panel**
- [ ] **_HYD/FUEL panel:_** CTR TK MODE SEL pushbutton “MAN” annunciator should be white
- [ ] **_HYD/FUEL panel:_** Battery voltage display is too wide
- [ ] **_HYD/FUEL panel:_** (not visible) RAT MAN ON pushbutton: below the cap should be the same type as the (round) call pushbuttons, not a Korry
_____________________
**CARGO SMOKE/VENT/ENG (ovhd) panel**
- [ ] **_CARGO SMOKE/VENT/ENG (ovhd) panel:_** (not visible) both DISCH pushbuttons: below the cap should be the same type as the (round) call pushbuttons, not a Korry
- [ ] **_CARGO SMOKE/VENT/ENG (ovhd) panel:_** Font size of CARGO SMOKE, VENTILATION, ENG, WIPER & RAIN RPLNT too small
- [ ] **_CARGO SMOKE/VENT/ENG (ovhd) panel:_** BLOWER pushbutton: OFF legend should be OVRD instead
- [ ] **_CARGO SMOKE/VENT/ENG (ovhd) panel:_** EXTRACT pushbutton: OFF legend should be OVRD instead
- [ ] **_CARGO SMOKE/VENT/ENG (ovhd) panel:_** ENG N1 MODE pushbuttons don’t exist in the NEO (LEAP & PW1100). These are exclusively for the CEO IAE V2500 engine
- [x] **_CARGO SMOKE/VENT/ENG (ovhd) panel:_** Position marks of the wiper switch scale should be bold

_____________________
**ENG (center pedestal) panel**
- [ ] **_ENG (center pedestal) panel:_** Missing label “MASTER 1 (2)” above the engine master switches
- [ ] **_ENG (center pedestal) panel:_** Engine annunciators (NO PUSH function!!) don’t have emissive texture during light test (red FIRE/amber FAULT)
- [x] **_ENG (center pedestal) panel:_** Position marks of the engine mode selector scale should be bold
_____________________
**Radio Management Panel**
- [ ] **_RMP:_** LOAD pushbutton is missing (used for CPDLC)
- [ ] **_RMP:_** STBY NAV label and line missing above the standby navigation pushbuttons
- [ ] **_RMP:_** Indicator lights should be above the pushbuttons and have the shape of a triangle
- [ ] **_RMP:_** SEL indicator should be amber
_____________________
**Audio Control Panel**
- [x] **_ACP:_** HF1, HF2 INT, CAB and PA microphone pushbuttons do not light up during light test or when selected
- [x] **_ACP:_** ON indicator in VOICE pushbutton does not light up during light test
- [ ] **_ACP:_** _NEW:_ VOICE push button should have an ON legend rather than three green lines
- [ ] **_ACP:_** Minor visual flaws with the rotary knobs
- **_ACP:_** Ignore the missing MLS label in the real picture. Let’s just pretend our Airbus is equipped with microwave landing system
_____________________
**ECAM Control Panel**
- [ ] **_ECP:_** All pushbutton indicator lights should be white

**Comment by lukecologne** [comment]
For reference: Related issue #956 for emissives only

**Comment by komp1821** [comment]
Updated

**Comment by tracernz** [comment]
>  ECP: All pushbutton indicator lights should be white

Is this just 3 white lines instead of 3 green lines?
