### ISSUE TITLE
[TRACKING] SYSTEMS INTEGRATION

### ISSUE THREAD

**Issue by ThePilot916** [flybywiresim/a32nx#1855]
**SYSTEMS INTEGRATION TODO**

- [ ] update .cfg for elec to set supply to always on(everything else will be managed by wasm)
- [ ] add elec templates with circuit map to all associated electric units across xmls
`
ref discord pinned message under general-sys
`
- [ ] capture flight control input and send based on HYD status(the right way to do this is to make the fbw module send new set of events which will be captured by the wasm_sys and then sent ahead based on HYD status, but until fbw is done we'll directly capture input and then send it to the sim based on HYD)
 - [ ] if we can manage to merge fbw with wasm_sys then we can skip on the new set of events too, but I think latency might get higher since theres no way to async run them without thread support
- [ ] remove redundant js logic implementation and clean it up to only retain display logic
- [ ] update xml to use the new vars to trigger events instead of the default ones (wondering if all the event triggers be entirely shifted to be handled by wasm, then we can skip on a number simvars being set)
- [ ] handle fuel pump event trigger on ELEC status
- [ ] load value addition template for all functional elec units
- [ ] Add init values for different spawn modes

**Comment by wpine215** [comment]
Will begin work on this today.

**Comment by Benjozork** [comment]
This is not relevant anymore
