### ISSUE TITLE
[META] Flight Model

### ISSUE THREAD

**Issue by derl30n** [flybywiresim/a32nx#3105]
## Tasks
- [ ] falsie center-of-lift (col) vs center-of-gravity (cg)
Issues:
   - High takeoff rotation rate (#2817)
   - pitch up at low speeds
   - more unnamed side effects. (#3092)
- [ ] Integration with [new engine model](#3117)

#### Currently limited by simulation engine:
- Individual Flaps & Slats -> Differentiate between Config 1 and 1 + F
- Pitch targets (claoa) for intermediate flaps

## Resolved
- [x] Wing dips on flare (#974)
   - Bad input handling within asobos FBW.
   Resolved by our own FBW

cc. @donstim

**Comment by sidnov** [comment]
@donstim Since you've worked on the flight model for quite a long time now, does this meta issue seem relevant or can it be closed?

**Comment by donstim** [comment]
IMO, it can be closed.
