### ISSUE TITLE
[META] Engine Model & FADEC

### ISSUE THREAD

**Issue by Taz5150** [flybywiresim/a32nx#3117]
## Description
META follow-up for issues and features to be taken care of and developed for the Leap-1A26 Engine and FADEC. Task roadmap is structured to be taken care of sequentially from top to bottom, due to prerequisites, dependencies and priorities.

Additional tasks or sub-tasks might be included and/ or priority order could be modified.

## Legend
:heavy_check_mark: Issue/ feature completely solved/ developed and integrated in the master in its final and definitive version
:warning: Issue/ feature partially solved/ developed and integrated in the master or dev branch
:x: Issue/ feature pending
:hourglass: Work in progress

## Task Roadmap
Tentative roadmap is as follows (it will be updated accordingly):

#### Engine Primary Parameter Modeling
 - [ ] N1 and N2 (https://github.com/flybywiresim/a32nx/issues/2047) :hourglass:
 - [ ] EGT :hourglass:
 - [ ] Fuel Flow (https://github.com/flybywiresim/a32nx/issues/2351), (https://github.com/flybywiresim/a32nx/issues/2239), (https://github.com/flybywiresim/a32nx/issues/2206)
  
#### Engine Secondary Parameter Modeling
 - [ ] Oil Qty, Pressure and Temperature (https://github.com/flybywiresim/a32nx/issues/2484)
 - [ ] Vibration Parameters

#### FADEC/ EEC
 - [ ] Start-up and Ignition (https://github.com/flybywiresim/a32nx/issues/254)
    - [ ] Auto :hourglass:
    - [ ] Manual 
 - [ ] Power Management (manual and auto)
 - [ ] Idle Management
     - [ ] Minimum Idle (https://github.com/flybywiresim/a32nx/issues/243) :hourglass:
     - [ ] Approach Idle
 - [ ] Thrust Reverse Management

#### Misc/ Non-Normal Ops
 - [ ] Independent Engine Control (https://github.com/flybywiresim/a32nx/issues/2339), (https://github.com/flybywiresim/a32nx/issues/1970)
 - [ ] Windmilling/ Gravity Feeding (https://github.com/flybywiresim/a32nx/issues/833), (https://github.com/flybywiresim/a32nx/issues/2841)

## Additional context and Disclaimer
For anything related to this META, do not hesitate in 'pinging' me. 
<u>Discord username</u>: **TazX#0405**
