### ISSUE TITLE
[META] Custom autopilot and autothrust

### ISSUE THREAD

**Issue by aguther** [flybywiresim/a32nx#3334]
This is a meta issue for the custom autopilot system incl. custom autothrust system.

### Common
- [x] Disable default ATHR in config file
- [x] Improve ​ɣT calculation in curves (partially solved)

### Flight Management
- [ ] LNAV
  - [x] Provide condition if NAV is available
  - [x] Provide proper input for NAV mode (transitions etc.)
- [ ] provide the following information
  - [x] FMGC Flight Phase
  - [x] V2
  - [x] VAPP
  - [x] VLS
  - [x] Altitude Constraint
  - [x] Thrust Reduction Altitude
  - [x] Acceleration Altitude
  - [x] Go Around Thrust Reduction Altitude
  - [x] Go Around Acceleration Altitude
  - [x] Engine Out Acceleration Altitude
  - [ ] Approach type (ILS / RNAV)

_VNAV to be implemented later._

### Autopilot
- [x] environment
  - [x] pause detection
  - [x] slew detection
- [ ] provide the following inputs to the FG part and ensure it's used
  - [x] FMGC Flight Phase
  - [x] V2
  - [x] VAPP
  - [x] VLS
  - [x] Altitude Constraint
  - [x] Thrust Reduction Altitude
  - [x] Acceleration Altitude
  - [x] Go Around Thrust Reduction Altitude
  - [x] Go Around Acceleration Altitude
  - [x] Engine Out Acceleration Altitude
  - [ ] Approach type (ILS / RNAV)
- [x] Integration with ATHR system
  - [x] Provide desired mode (SPEED, THRUST, ...) to ATHR system
- [x] Handling of FD/AP on/off
  - [x] FD off
  - [x] FD on -> FD off
  - [x] FD off -> FD on
  - [x] FD on -> AP on
  - [x] FD off -> AP on
- [ ] NAV mode
  - [x] Add Phi-N input for bank angle from FM
  - [ ] Align H/PATH law to input
  - [ ] Clarify arm / engage condition (10 NM <> 1 NM)
  - [x] Implement arm / engage and allow only when flight plan available
  - [x] Support DIR-TO
- [ ] Managed CLB / DES
  - [x] Provide interface to FM part to select appropriate sub-mode for DES
  - [x] Check if a V/PATH law is needed
- [ ] Improve GA conditions
  - [x] AP1+2 disengage logic
  - [x] SRS mode disengage on GA ACC ALT (this altitude needs to be provided, not available yet)
  - [x] Allow ALT to engage when > 400 ft RA
  - [ ] NAV arm / engage logic (< 100 ft, > 100 ft)
  - [x] Use correct speed for different conditions
  - [x] Revert HDG/TRK mode if needed
  - [x] Revert to OP CLB on change or engage of selected SPEED
- [x] SRS Mode
  - [x] Revert to OP CLB on change or engage of selected SPEED
  - [x] Correctly use thrust reduction / acceleration altitudes (check also initial settings)
  - [x] Add information if FLX is valid and active and switch to SRS / RWY in FLX/MCT only in this case
- [ ] LAND mode
  - [ ] Disable HDG pre-selection on MAP (source for MAP?)
  - [x] Ensure G/S does not use invalid signal
  - [x] Tune G/S law coming closer to runway, take care it works also in gusts
  - [x] Improve LOC* capture performance (reduce gain?)
  - [x] Reduce LOC* capture turn towards beam
  - [x] Calculate and provide landing capability
  - [x] Behavior after Autoland (disconnection of AP/ FMA indications)
  - [x] Tune Autoland for different conditions (especially FLARE law)
  - [x] Change flare law to take radio altitude as reference (sloped runways)
  - [ ] Support other approach types (like RNAV)
  - [x] Support pull of V/S with revert to HDG/TRK
  - [x] Implement correct landing capability reversion (e.g. CAT3-D -> CAT3-S -> CAT1)
  - [x] Improve ROLL OUT mode guidance (high and slow speed)
  - [x] Latch landing capability below 100 ft until AP is disconnected
- [x] SPD/MACH mode
  - [x] energy management has been greatly improved
  - [x] test if usage of ​ɣT is possible (ensure acceleration sim variables are ok)
  - [x] energy management should be 70% speed and 30% climb -> test limiter for ΔV from ɣT
  - [x] Align engagement with ATHR system (thrust change rate)
- [x] ALT Mode
  - [x] Support ALT CRZ FMA display
  - [x] Support Soft ALT for ALT CRZ (first test done, activation without custom ATHR does not make sense; conditions for soft ALT need to be extended and more signals are needed)
  - [x] Allow ALT to engage when > 400 ft RA
  - [x] Check if ALT should be directly engaged when abs(FCU ALT - Current ALT) < 20 ft
  - [x] When AP off -> on and deviation > 250 ft from FCU altitude: cancel V/S and hold
- [x] Improve flying in turbulence
  - [x] ALT has been improved by adding a lag-filter
- [ ] Model
  - [ ] Clean-Up data structures to only contain what is needed
  - [ ] Rework state machine to use full bus signal
  - [ ] move all state transitions to distinct function
- [ ] Other
  - [x] delay FMA indications on PFD
  - [x] improve RWY mode guidance for FD
  - [x] check transition when LOC is lost in RWY mode < 30 ft
  - [x] add protections for guidance (high speed, low speed) and corresponding mode reversions
  - [x] increased FCU delay to 45 s for HDG and V/S

### Autothrust
- [x] Throttle Mapping
  - [x] Base functionality like custom fbw
  - [x] Support configuration per axis
  - [x] Support configuration with start and end per detent instead of deadzone
  - [x] Integrate EFB settings page
- [x] Support keys like F1 to put levers to IDLE directly
- [x] Disconnect throttle animation from sim throttle variable (so levers do not move by ATHR action) -> do not alter linearity for now, use a look-up table to match current animation behavior
- [x] Provide separate variable for commanded N1 (usage by EWD)
- [x] Provide separate variable for TLA based N1 (usage by EWD)
- [x] Support MACH mode
- [x] Control system improvements
  - [x] Improve behavior in cruise (less up and down of N1)
  - [x] Support ALT SOFT mode
  - [x] Improve behavior in turbulence
  - [x] Relax strictness in speed control a bit
  - [x] Improve transition between thrust modes and speed mode
  - [x] take into account ɣT
  - [x] take into account load-factor
  - [x] Support approach mode
- [x] Engine Model
  - [x] Provide proper thrusts limit for MREV, IDLE, MCT, TOGA
  - [x] Support FLEX TO
- [x] Integration
  - [x] Provide FMA indication information
  - [x] Provide LVR CLB information (maybe not directly in ATHR system) but it's needed
  - [x] Adapt EWD to use N1 TLA
  - [x] Adapt EWD to use commanded N1 in case ATHR is engaged and active -> code added but display seems broken; needs to be done with a rewrite of the display itself
  - [x] Improve FCU Speed knob (not dialing by 10 sometimes), add 10 s timeout
  - [x] Implement proper MACH switching
  - [x] Fix ATHR button being a toggle button instead of push button,
  - [x] Do not fire event from ATHR push button on FCU in case of LAND TRACK mode
  - [x] Clean-up throttle lever animation template
  - [x] Switch all components using throttle position to new TLA variable (with appropriate TLA angles)

**Comment by wpine215** [comment]
Is this meta-issue still needed?
