### ISSUE TITLE
[BUG] Meta-issue for FMA thrust setting messages

### ISSUE THREAD

**Issue by Benjozork** [flybywiresim/a32nx#397]
**Branch**
master

**Describe the bug**
FMA does not display accurate thrust setting 

- [ ] LVR MCT - (issue #351)
   - [x] (**PR #399**) `One engine running && (A/C speed > Green dot speed) && (Throttle < FLX MCT detent) && (In takeoff || In go-around)`
   - [ ] Should also display a caution
   - re.  Ares#3394 on discord
   - re. http://www.a320dp.com/A320_DP/nav-autoflight/sys-13.3.14.html
- [ ] LVR CLB   - should only display above thurst reduction altitude (#???)
   - [ ] (**PR #441**) Should also display a caution
   - re.  Ares#3394 on discord
   - re. http://www.a320dp.com/A320_DP/nav-autoflight/sys-13.3.13.html

TODO : Add more possible discrepancies

**To Reproduce**

 - LVR MCT - should only display in case of single-engine operations
   - TODO, but really anything that's not single-engine operation
 - LVR CLB   - should only display above thurst reduction altitude
   - Start take-off
   - Wait until A/C is above 30 kts
   - Cut thrust entirely
   - Observe that FMA states "LVR CLB" when A/C below 30 kts

**Expected behavior**

FMA respects A320 behaviour for each message

**Screenshots or Videos**
N/A

**Additional context**

LVR MCT code

```js
IsActive_LVRMCT() {
    var takeoff = (Airbus_FMA.CurrentPlaneState.flightPhase == FlightPhase.FLIGHT_PHASE_TAKEOFF);
    var goaround = (Airbus_FMA.CurrentPlaneState.flightPhase == FlightPhase.FLIGHT_PHASE_GOAROUND);
    if (takeoff || goaround) {
        var greenDotSpeed = goaround ? Simplane.getFMCApprGreenDotSpeed() : Simplane.getFMCGreenDotSpeed();
        if (Airbus_FMA.CurrentPlaneState.highestThrottleDetent < ThrottleMode.FLEX_MCT) {
            if (SimVar.GetSimVarValue("AIRSPEED TRUE", "Number") < greenDotSpeed) {
                return true;
            }
        }
    }
    return false;
}
```

LVR CLB code

```js
IsActive_LVRCLB() {
    if (Airbus_FMA.CurrentPlaneState.flightPhase == FlightPhase.FLIGHT_PHASE_TAKEOFF) {
        if (Airbus_FMA.CurrentPlaneState.highestThrottleDetent < ThrottleMode.CLIMB && Simplane.getIndicatedSpeed() > 30) {
            return true;
        }
    }
    else if (Airbus_FMA.CurrentPlaneState.flightPhase == FlightPhase.FLIGHT_PHASE_CLIMB) {
        if (Airbus_FMA.CurrentPlaneState.highestThrottleDetent > ThrottleMode.CLIMB) {
            if (Airbus_FMA.CurrentPlaneState.radioAltitude >= Simplane.getThrustReductionAltitude()) {
                return true;
            }
        }
    }
    else if (Airbus_FMA.CurrentPlaneState.flightPhase == FlightPhase.FLIGHT_PHASE_GOAROUND) {
        if (Airbus_FMA.CurrentPlaneState.highestThrottleDetent > ThrottleMode.CLIMB) {
            if (Airbus_FMA.CurrentPlaneState.radioAltitude >= Simplane.getThrustReductionAltitude()) {
                return true;
            }
        }
        else if (Airbus_FMA.CurrentPlaneState.highestThrottleDetent < ThrottleMode.CLIMB) {
            return true;
        }
    }
    return false;
}
```

**Comment by Benjozork** [comment]
cc. @nobodyn0se @Curtis-VL

**Comment by MisterChocker** [comment]
Status on this?

**Comment by MisterChocker** [comment]
Outdated. Will be replaced by #3334
