### ISSUE TITLE
[META] Navigation Display

### ISSUE THREAD

**Issue by tracernz** [flybywiresim/a32nx#4164]
I am working through the ND at the moment making small improvements that make sense without a rewrite (I wish I had time for that!). At the moment this is a small list of those improvements.

Smaller improvements that may be feasible with Asobo ND code:
- [x] Rose range double what it should be (#935, #4377, fixed #4383)
- [ ] VOR/ILS deviation scale aligned to course - heading
- [x] Plane and lubber line colour should be same (fixed #4385)
- [ ] TO WP should be white (green drawn over?) (#1730, #4108)
- [ ] Masks not accurate (map, Wx/Terr, ...)
- [ ] Selected origin/dest runways should be drawn (#1713)
- [x] Graduations on rotating circle should be smaller (fixed #4383)
- [x] Fixed arrow markers at 45° increments on rose (#4071, fixed #4383)
- [x] Map draw scale slightly off (WPs appear closer than they should according to circles) (#3219, fixed #4383)
- [x] In rose/plan mode: dashed range circle with radius 1/4 range, solid circle with radius 1/2 range (fixed #4383)
  - [x] Range text inside both circles at 225 radial (fixed #4383)
- [x] In arc mode: dashed arcs with radius 1/4, 1/2, 3/4 range (fixed #4383)
- [x] TCAS range ring at 2.5 NM at 10, 20 NM range (radial dashes at each hour position), replacing normal range arc on 10 NM, only when TCAS is enabled (fixed #4383)
- [x] Cross-track error shown next to airplane icon when > 0.02 NM (fixed #4383)
- [x] Cross-track error shown at bottom left of PLAN mode (where VOR/ADF normally is) (fixed #4383)
- [ ] Fix info radius and radial (MCDU work too) (#1181)
- [ ] Flight plan should be drawn over top of VOR/ADF needles
- [x] VOR/ADF info should not be shown in PLAN mode (fixed #4383)
- [ ] ILS/VOR course pointer should extend inside inner range ring
 
Larger improvements for future (React rewrite, WASM + nanoVG, or ???):
- [ ] Custom terrain and Wx radar with accurate hatching etc.
- [ ] Proper path plotting with FPM/LNAV predicted arcs
- [ ] Energy circle (needs VNAV)
- [ ] FLS (needs LNAV/VNAV impl. too)
- [ ] ??

TODO: collect issue numbers

References:
TCAS TA/RA, 10 NM range:
![image](https://user-images.githubusercontent.com/9995998/113677475-b9a88780-9711-11eb-8d4b-72a833c75815.png)
TCAS Off, 10 NM range:
![image](https://user-images.githubusercontent.com/9995998/113677559-d218a200-9711-11eb-88aa-38fd3cfc9ed6.png)
Range change:
![image](https://user-images.githubusercontent.com/9995998/113677605-df359100-9711-11eb-910b-c9308f5e5955.png)
TCAS Off, 20 NM range:
![image](https://user-images.githubusercontent.com/9995998/113677636-e8bef900-9711-11eb-967a-35b61ff43453.png)
TCAS On, 20 NM range:
![image](https://user-images.githubusercontent.com/9995998/113677666-f2486100-9711-11eb-93a1-3fea3cea0245.png)
