### ISSUE TITLE
[REQUEST] Implement the ANN LT

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#528]
~~- [ ] make the test position require you to hold the mouse button down (its spring loaded, i think?)~~
- [x] dim and brt setting should change the brightness level of all the button that have lights
- [x] test position should make all button lights turn on #566

ANN LT TEST
- [x] make most buttons light up #566
- [x] make sure no double blue dots are visible on the buttons #566
- [x] make displays show test stuff
  - [x] FCU #590
    - [x] IRL has a decimal point to the left of every number, but the game FCU only has one's that are actually used, so we will have to add the other decimal elements to match IRL #590
  - [x] BARO display #590
  - [x] battery displays?
- [x] more button/square thingy lights
  - [x] ATC MSG x2
- [ ] make sure ANN LT TEST is in the checklist
- [x] sidestick priority arrows
- [ ] Overhead
  - [x] EVAC COMMAND (should have OFF for seq2, probably has blue dots in vanilla)
  - [x] ADIRS ON BAT (couldn't find anything in gltf or interior xml for it)
  - [x] ADIRS IR buttons should say OFF for seq2 (vanilla is ALIGN)
  - [x] PA should probably have something (vanilla just has blue dots for seq2 and nothing else)
  - [x] 5x FIRE AGENT buttons should say DISCH (vanilla says "neo")
  - [ ] 3x big rectangular FIRE things need emissive textures or something
  - [x] ELEC PUMP should have ON in white for seq2 (vanilla is blue ON)
  - [x] FUEL MODE SEL should have MAN in white (vanilla is MAN in blue)
  - [x] FUEL XFEED should have ON in white (vanilla is ON in blue)
  - [x] ELEC
    - [x] COMMERCIAL should not have anything in seq1 (vanilla has FAULT) (needs verification? maybe the light was broken in the vid?)
  - [x] AIR COND
    - [x] RAM AIR should have ON in white for seq2 (needs confirmation)
  - [x] CABIN PRESS MODE SEL should have MAN in white (in vanilla its blue)
  - [x] DITCHING has some kind of white light (vanilla is blank or blue dots)
  - [x] SIGNS has something in orange? but vanilla is a white OFF
- [x] Chronometer should have lots of 88888 #590
- [ ] MCDU has 5 lights on top and some on the sides
- [x] radio thing should show all 88888888 #590
- [x] push buttons by engine starters
- [x] COCKPIT DOOR square thing should not have green on it
- [x] RUD TRIM should show something like R 88.8
- [x] ATC FAIL light should be on #590
- [x] TCAS display should be 8888 #590
- [ ] down arrow by gear lever should light up red

# References
ATC MSG
![image](https://user-images.githubusercontent.com/3533988/92770031-2b2c7d00-f35f-11ea-9bd7-614c392e7f92.png)

FCU and other things: https://www.youtube.com/watch?v=RmuH2St76Rs

![image](https://user-images.githubusercontent.com/3533988/92771528-93c82980-f360-11ea-8ca7-4147afe3df07.png)

![image](https://user-images.githubusercontent.com/3533988/92950748-cf2b2c80-f422-11ea-8960-3d1920f539e7.png)

**Comment by AdenFlorian** [comment]
working on this now

**Comment by oliverpope03** [comment]
@AdenFlorian i figured out how to make the swith spring loaded (whilst adding another switch) if you think the ANN test light is which i thought it was too

**Comment by davidwalschots** [comment]
I'm closing this issue and have carried over any remaining items to individual issues:

Make sure ANN LT TEST is in the checklist: #5138
3x big rectangular FIRE things need emissive textures or something: #4597
down arrow by gear lever should light up red: #5139
MCDU has 5 lights on top and some on the sides: #5140
