### ISSUE TITLE
flyPadOS 3

### ISSUE THREAD

**Issue by ErickSharp** [flybywiresim/a32nx#6051]
### Aircraft Version

Development

### Description

- [ ] Language translation
- [ ] On-screen keyboard
- [x] Theming
- [x] Redone state management
- [ ] Page UI redesigns
- [ ] Chart bookmarking
- [ ] Boarding page
- [x] Automatic SimBrief data fetching option
- [ ] Additional power states
- [ ] ATC 'set standby' function
- [ ] General code cleanup and refactor
- [ ] Notifications and modals

### Discord Username (optional)

Erick [Z-6]#6484

**Comment by ErickSharp** [comment]
Onscreen keyboard is currently being worked on.

**Comment by lolisec** [comment]
Any updates on chartfox implementation been silent for sometime now?

**Comment by ErickSharp** [comment]
> Any updates on chartfox implementation been silent for sometime now?

Currently I am trying to make as much progress on the features that I outline in the tracking comment above. At the moment I am not sure if Chartfox will be able to be made available anytime soon as I am currently the only person working on this feature and we have run into some conflicts in trying to get it to work in the past. When I get through more of the features planned and am able to start looking into more things to implement, I will give out some more information regarding our plans for Chartfox implementation. 

Thanks!

**Comment by ErickSharp** [comment]
Closing this issue as the tracking has been moved to the pull request description of the relevant pull request.
