### ISSUE TITLE
[BUG] Meta-issue for brake temperature calculation

### ISSUE THREAD

**Issue by Benjozork** [flybywiresim/a32nx#632]
**Mod Version**

brake-temp-improvements (8308cdba)

**Describe the bug**

 - [x] Move core logic to A32NX_Core (PR ~~#631~~ #749)
 - [x] Move "brakes hot" logic to A32NX_Core
 - [x] Fix brake temperature not being affected by autobrake application (Issue #624, PR ~~#631~~ #749)
 - [x] Make heat-up a function of wheel RPM in addition to brake position (PR #749)
 - [x] Calculate heat-up and cool-down separately for different wheel sets (PR #749)
 - [x] Use actual heat transfer coefficient math (PR #749)
 - [x] Use actual ambient temperature, not 45C (PR #749)
 - [x] Only show in increments of 5 (PR #749)
 - [x] Clamp displayed temperature above 0 (PR #786)

**To Reproduce**

N/A

**Expected behavior**

N/A

**Actual behavior**

N/A

**References**

TODO

**Additional context**

N/A

**Comment by Benjozork** [comment]
@lukecologne, let's discuss here !

Do you think it would be interesting to use actual heat transfer / friction equations with data about the materials used in the brakes ?

**Comment by lukecologne** [comment]
Unfortunately I don't think it's that easy to model friction heating accurately. Heat transfer between the brakes shouldn't be too difficult if we have the material it's made of (carbon I think?). And the convective cooling to the air I also wouldn't know an equation off the top of my head, but I think that would be simpler than the friction heating. Radiative energy transfer can be neglected I think.

**Comment by Benjozork** [comment]
Yeah I think that sounds good. Do you have any prototype code for this ?

**Comment by lukecologne** [comment]
I had something basic, but my PC died yesterday, currently on my laptop, but I don't have it here. Maybe I'll have it up later today or tomorrow

**Comment by lukecologne** [comment]
Another question, is there even heat transfer between the two brakes on one wheel? Or is each of the 4 systems disconnected?

**Comment by UncleClapton** [comment]
@Benjozork 2 problems I've identified:

1. Applying parking break stops all temp decay, even when the aircraft is stationary. This isn't really all that realistic.
2. Brake temperature decay is based on `deltaTime`, so low screen refresh rate slows decay significantly. This MAY have been helped by moving the logic to `a32nxcore`, but not completely alleviate it. (see #529 for more info) I may have a universal solution for core modules coming up soon though.

**Comment by lukecologne** [comment]
About problem 1: I have some changes to this coming that will fix this, and hopefully make the decay more realistic. Though I still use deltaTime, so that would need fixing

**Comment by JackZ974** [comment]
Problem is when users change time in the sim, all the calculations will be offset. The only reliable source would be elapsed_time in that case, to handle all situations such acceleration in cruise.
.

**Comment by lukecologne** [comment]
I don't think users manually changing time should be taken into account, but simrate should. currently, all our timers are not affected by simrate. @Benjozork What do you think about taking my branch directly for a PR? That way we woulddn't have to wait until both of the PR's get tested, they just could be tested as one package

**Comment by Benjozork** [comment]
> I don't think users manually changing time should be taken into account, but simrate should. currently, all our timers are not affected by simrate. @Benjozork What do you think about taking my branch directly for a PR? That way we woulddn't have to wait until both of the PR's get tested, they just could be tested as one package

Sounds good to me ! You can rebase my changes into master and work off of that and we can close this.

**Comment by lukecologne** [comment]
Alright, then I'll do that. I'll open a draft PR straight away so people can test easily

**Comment by lukecologne** [comment]
Done. You should probably close the old PR

**Comment by Benjozork** [comment]
Only this left : 

 - [ ] Only show in increments of 5
 - [ ] Clamp displayed temperature above 0

**Comment by lukecologne** [comment]
Only show in increments of 5 is done, clamping is not

**Comment by MrMinimal** [comment]
Last item can be ticked as it has been implemented. Close?
