### ISSUE TITLE
Porting aircraft changes from 1.8.3.0

### ISSUE THREAD

**Issue by UncleClapton** [flybywiresim/a32nx#719]
This issue is to track changes made to files we have touched which were updated by the latest patch.

Double check the comments to ensure what you want to work on isn't taken by someone else already. Please comment on what you are working on before beginning a branch for it.

- [x] `PFD` instruments, AKA the reason @JackZ974 drinks (#770)
    - [x] `AirspeedIndicator.js` (#770)
    - [x] `AltimeterIndicator.js` (#770)
    - [x] `AttitudeIndicator.js` (#770)
    - [x] `ILSIndicator.js` (#770)
- [x] `FlightDirector=True` in `Climb`, `approach`, `cruise`, `final`, `taxi`, and `runway` FLTs. (#720)
    - [x] Manual fix we applied for this should be removed! (#771)
- [x] New var: `A320_NEO_CDU_START_PAGE=35` in `final.FLT`. (#720)
- [x] MANY `flight_model.cfg` changes. See Diff. (#720)
- [x] `A320_NEO_INTERIOR.xml` (#720)
    - [x] Asobo_GT_Update has new conditions. See Diff. (#720)
    - [x] `Overhead_Audio_Panel` add new override params. (#720)
    - [x] New tooltips on `AP` buttons and `ATHR`. (#720)
    - [x] Rename `ASOBO_AIRBUS_Switch_Altitude_Increment_Template` to  `ASOBO_AUTOPILOT_Switch_Altitude_Increment_Template` (#720)
- [x] `panel/panel.xml` (#720)
    - [x] `<AlwaysUpdate>True</AlwaysUpdate>` on CDU and FCU Insturments (#720)
- [x] `systems.cfg` (#720)
    - [x] Some light definitions got changed. @Snapmatics's changes might have made this obsolete though? (#720)
    - [x] Rename `autothrottle_disarm_on_idle` -> `autothrottle_managed_by_plane ` (#720)
- [x] MCDU (Various code pages changed. Hard to summarize) (#721)
    - [x] `A320_Neo_CDU_AvailableArrivalsPage.js` (#721)
    - [x] `A320_Neo_CDU_FlightPlanPage.js` (#721)
    - [x] `A320_Neo_CDU_InitPage.js` (#721)
    - [x] `A320_Neo_CDU_MainDisplay.js` (#721)
    - [x] `A320_Neo_CDU_PerformancePage.js` (#721)
- [x] `A320_Neo_UpperECAM.js` (#731)
    - [x] Some things are using Simplane over simvars directly now O.o (#731)
- [x] `A320_Neo_FCU.js` (#730)
    - [x] `requestAnimationFrame()` need to be replaced with `this.gps.requestCall()`. (#730)
    - [x] `_gps` needs to be saved to class property from constructor. (#730)
    - [x] Some `Math.round` instead of `Math.floor` calls. check diff. (#730)
    - [x] `this._enterIdleState()` called at certain points. (#730)
    - [x] `if (Math.abs(deltaAltitude) < 100) {` -> `if (Math.abs(deltaAltitude) < 200) {` (#730)
- [x] `A320_Neo_SAI.js` is a clusterF#*@ (#737)
- [x] `A320_Neo_PFD.css` various css positioning adjustments. dunno if this will conflict with ours much
- [x] `A320_Neo_PFD.js`
- [x] `Airbus_FMA.js` (#736)
    - [x] Changes to temp text, `getTargetRow1State` `GetModeState_ALT`, `GetModeState_GS`, and `GetModeState_APPNAV` (#736)
- [x] `MFD/NDCompass.js` (#738)
    - [x] `this.trackingLine` was removed entirely O.o (#736)
- [x] `MFD/NDInfo.js` (#736)
    - [x] `if (ils.id == 1 || ils.id == 2 || this._navSource == 1) {`: `ils.id == 2` -> `ils.id == 3` (#736)
- [x] `Asobo/Airliner/Airbus.xml` `ASOBO_AIRBUS_Switch_Altitude_Increment_Template` was completely removed. (#720)
- [x] `Asobo/Airliner/AirlinerCommon.xml` Changes to knobs (#720)
- [x] `Asobo/Common/Handling.xml` changes to `ASOBO_HANDLING_Lever_Flaps_Continuous_Template` (#720)
- [x] `Subtemplates/Deice_Subtemplates.xml` possibly work on extracting out changes @AdenFlorian made so we don't have to touch this file directly. I think subtemplates should be avoided. The code change in this file is for a completely different aircraft... (#720)
- [x] `Subtemplates/Electrical_Subtemplates.xml` Multiple changes. Same issue as above (#720)
- [x] `Subtemplates/Fuel_Subtemplates.xml` single line change for `ln1049`. Same issue as above. (#720)

File Diff: https://github.com/flybywiresim/a32nx/compare/asobo-1.7.12...asobo-1.8.3

**Comment by Middi25X** [comment]
Have question: Where do put: 
asobo-aircraft-a320-neo
asobo-vcockpits-instruments-a320-neo
asobo-vcockpits-instruments-airliners
fs-base-aircraft-common ? is it to Community folder or only Asobo-aircraft-a320-neo?

**Comment by Venorcis** [comment]
Might be useful too, the directly relevant parts of the official changelog (from https://www.flightsimulator.com/patch-version-1-8-3-0-is-now-available/):
- General : AP behavior improvements.
- Airbus A320neo : automatic speed management improvements.
- Airbus A320neo : alpha floor condition is now correctly triggered.
- General : weight is better taken into account for V speed calculations. 
- Airbus A320neo : target altitude can now be changed when AP is disabled.  
- Airbus A320neo : armed modes no longer appear in boxes on the FMA.  
- Airbus A320neo : flaps « FULL » indication instead of « F » on ECAM.  
- Airbus A320neo : FMGS message « INVALID ENTRY » replaced by « NOT ALLOWED ».  
- Airbus A320neo : FMGS now only displays arrival procedures corresponding to the selected runway.  
- Airbus A320neo : FMGS now correctly displays ETA for approach points.  
- Airbus A320neo : removed remaining waypoints on ND after selecting different approach procedures.  
- Airbus A320neo : fixed heading bug alignment offset issue.  
- Airbus A320neo : fixed missing runway in the perf page of FMGS when a departure runway is already selected.  
- Airbus A320neo : fixed constraints flickering on ND.  
- Airbus A320neo : FMGS block fuel indication now correctly initialized.

**Comment by Middi25X** [comment]
yes but where to put all this folder? xD

**Comment by UncleClapton** [comment]
> Have question: Where do put:
> asobo-aircraft-a320-neo
> asobo-vcockpits-instruments-a320-neo
> asobo-vcockpits-instruments-airliners
> fs-base-aircraft-common ? is it to Community folder or only Asobo-aircraft-a320-neo?

None of these are things you should ever touch manually. This ticket is not installation or update instructions.

**Comment by Middi25X** [comment]
ahh just put it in steam-Official and replaced with current folder but took backup off it, so what is the latest update to use with the new version ?

**Comment by wpine215** [comment]
> 
> 
> ahh just put it in steam-Official and replaced with current folder but took backup off it, so what is the latest update to use with the new version ?

You should never be looking at or touching the packages in the official folder or any branches on this github prefixed with "asobo"

**Comment by UncleClapton** [comment]
theres nothing you should be putting anywhere @Middi25X, Everything you listed are things that the game downloads for you. rule of thumb is, if you do not know what you're doing with the files in the `Official` folder, you shouldn't even go in there. Placing anything wrong within that folder could damage your install.

**Comment by Middi25X** [comment]
put all back again for sure :)) But A320N 1.7 is this one go for Community right ?

**Comment by UncleClapton** [comment]
@Middi25X Right now the mod is broken and incompatible with the current version of the game. I don't recommend using the mod at all until we can get an update out.

**Comment by Middi25X** [comment]
Okei thx for all help and info just wait then :D !

**Comment by UncleClapton** [comment]
Working on FLTs, flight model, and systems.cfg now.

**Comment by tyler58546** [comment]
Just finished MCDU #721

**Comment by UncleClapton** [comment]
Working on `A320_NEO_INTERIOR.xml`, `Panel.xml`.

**Comment by Benjozork** [comment]
I'm gonna work on `Airbus_FMA.js`.

**Comment by lukecologne** [comment]
>     * [ ]  `A320_Neo_UpperECAM.js`
>       
>       * [ ]  Some things are using Simplane over simvars directly now O.o
> 
The upper ECAM shouldn't be a problem, SimPlane is mostly just a wrapper for SimVar calls. Sometimes it's a bit more logic than that but it should be fine. If you want, I can open a PR and add these Simplane functions to `types.d.ts`

**Comment by DoToAdventures** [comment]
Done FCU.js #730

**Comment by UncleClapton** [comment]
Looking into PFD files

**Comment by lukecologne** [comment]
UpperECAM done #731

**Comment by UncleClapton** [comment]
Just finished work on SAI (ISIS)

**Comment by UncleClapton** [comment]
Working on MFD/ND now.

**Comment by Middi25X** [comment]
Good job! :D How long will it take before release?

**Comment by JackZ974** [comment]
For the PR that affect the PFD:
- PR#613 can be included IMO, since it is working as is and the code changes do not break anything in the PFD code
- ASOBO fixed the horizon desync in the PFD.js code, so I guess that the Fix horizon PR#611 is no longer needed
- PR#616 is broken
- PR#612 is broken
- PR#558 can be incorporated, provided name change of variable (I'm on it)

**Comment by JackZ974** [comment]
Port of PR#558 ready to be tested

**Comment by AdenFlorian** [comment]
i will close this since the last porting pr (MCDU) has been merged
