### ISSUE TITLE
[MISC] Meta-issue for code formatting / linting

### ISSUE THREAD

**Issue by Benjozork** [flybywiresim/a32nx#761]
**Description**

This is a meta-issue for discussing eventual integration of code formatting / linting in the project.

**Motivation**

Much of the Asobo code is weirdly formatted. This ranges from XML to JS and CSS files. Many PRs also break good practice or feature weird formatting choices, and even sometimes lack of care for properly formatted code.

 Notable examples of broken best practice :

 - use of `var` instead of either `let` or `const`
 - use of `for (let i = 0; i < n; i++) {...}`-style loops over iterable loops where `i` is not used outside of indexing
 - confusing and seemingly arbitrary use of code blocks
 - weird declaration of classes

**Steps to take**

 - [ ] Write an official ESLint config for JS
 - [ ] Discuss integration in GitHub PR checks
 - [ ] Discuss effect and policy on Asobo code
 - [ ] Figure out solution for formatting / linting of XML, CSS and soon C++ (HTML is probably not necessary))

cc. @wpine215, @UncleClapton

**Comment by tracernz** [comment]
Not really relevant anymore.
