### ISSUE TITLE
[META] MCDU/FMGS

### ISSUE THREAD

**Issue by wpine215** [flybywiresim/a32nx#823]
* Will be updated with more specific tasks *

**Mod Version**

Master (separate branch will be created soon)

**Pages:**
- [ ] Data page
- [ ] Init A page
- [ ] Init B page
- [ ] Flight plan page
- [ ] Sec f-plan page
- [ ] Lat Rev page
- [ ] Vert Rev page
- [ ] Rad nav page
- [ ] Fuel pred page
- [ ] Prog page
- [ ] Perf page

**To Reproduce**

N/A

**Expected behavior**

N/A

**Actual behavior**

N/A

**References**

TODO (contact Ares#3394 for specific info/references if needed)

Discord username (if different from GitHub): Iceman#5540

**Comment by alainzu** [comment]
![FMGC2](https://user-images.githubusercontent.com/71940317/95102062-33e05b00-0733-11eb-9b3e-d831f495bdf9.jpg)

That should be the priority number 1  !
To be able to flight correctly with the A320, we need a fully functional MCDU:
be able to insert route, insert the airway that defines the next waypoints of the route (+++) 
be able to do a lateral revision on a waypoint
be able to do a vertical revision to correct altitudes
be able to correctly insert SID, STAR, transitions
This is not correctly possible todays and considerably limits the possibility to fly with A320

**Comment by MisterChocker** [comment]
Do we want to update this meta issue or do we close it as it is outdated?.

**Comment by MisterChocker** [comment]
Closing since no response from op.
