### ISSUE TITLE
[META] Emissive Textures 

### ISSUE THREAD

**Issue by NathanInnes** [flybywiresim/a32nx#956]
# Meta Issue for Emissive Texture Work

#### Engine Control Panel (Master Switches)
- [x] Both DUMMY buttons should say FIRE in RED & have FAULT in Amber. - *Ref. 2. Engine Control Panel Image*
#### CKPT DOOR
- [x] OPEN in Amber.
- [x] FAULT in RED.
#### GRAVITY GEAR
- [x] Text on turn handle shouldn't be lit up. - *Ref. 3. Image of Pedestal*
#### Transponder 
- [x] ATC FAIL should be AMBER not PINK. - *Ref. 4. Youtube video demo. https://www.youtube.com/watch?v=PyR6BXlYI2o*

## GLARESHIELD
- [x] Master Caution should be in Amber.
- [x] Side stick priority should have ARROW pointing to who has priority in RED - *Ref. 5. Image of priority*
- [x] Outermost button should have an "ATC MSG" emissive in blue - *Ref 1.*

## CLOCK
- [ ] RST, CHR, DATE, GPS/INT, RUN/STP/RST shouldn't light up. 

## SAI - *Ref. 7 Image of SAI*
- [x] ATT and BARO shouldn't light up. (After #1081 gets merged)

### CALLS
- [x] EMER should say CALL instead of OFF in AMBER on the top, and BOXED WHITE ON instead of OFF on the bottom

### OXYGEN
- [x] CREW SUPPLY should say "OFF" with TWO WHITE DOTS ABOVE.
- [x] PASSENGER should say "SYS ON" in WHITE with TWO DOTS BELOW.

### RCDR
- [x] GND CTL should have TWO BLUE DOTS above BOXED ON.

### GPWS
- [x] LDG FLAP 3 should say "ON" in WHITE with TWO WHITE DOTS ABOVE.
- [x] FLAP MODE should say "OFF" in WHITE with TWO WHITE DOTS ABOVE.
- [x] G/S MODE should say "OFF" in WHITE with TWO WHITE DOTS ABOVE.

### EMER ELEC PWR
- [x] RAT should be RED FAULT with TWO WHITE DOTS UNDER.
- [x] GEN 1 LINE SMOKE should be AMBER.

### EVAC
- [x] COMMAND should say "EVAC" in BOXED RED with BOXED ON UNDER.

### ADIRS 
- [x] ALIGN should say OFF in BOXED WHITE. *Ref. 9 Schematic of ADIRS*
- [x] ON BAT in AMBER.

### FIRE
- [x] DISCH should be BOXED AMBER.

### HYDRAULICS
- [x] ELEC PUMP should be BOXED WHITE ON.

### FUEL
- [x] MAN should be BOXED WHITE.
- [x] CTR PUMP 2 is missing FAULT light.
- [x] XFEED should be BOXED WHITE "ON".
- [ ] XFEED should be GREEN OPEN

### ELEC
- [x] COMMERCIAL should be BOXED OFF with TWO WHITE DOTS ABOVE.
- [x] IDG1 & 2 should have TWO WHITE DOTS UNDER.
- [x] BUS TIE should have TWO WHITE DOTS ABOVE.

### AIR COND.
- [x] RAM AIR should be BOXED ON with TWO WHITE DOTS ABOVE.
- [x] PROBE WINDOW should have TWO WHITE DOTS ABOVE.

### CABIN PRESS.
- [x] MODE SEL should be BOXED WHITE MAN.
- [x] DITCHING should be BOXED WHITE ON with TWO WHITE DOTS ABOVE.

### SIGNS
- [x] EMER EXIT LT should be AMBER OFF with TWO WHITE DOTS ABOVE.

### CARGO SMOKE
- [x] DISCH should be AMBER.

### VENTELATION
- [x] BLOWER should be BOXED "OVRD" in WHITE.
- [x] EXTRACT text missing and should be same as BLOWER.
- [x] CAB FANS should have WHITE DOTS ABOVE.

## OVERHEAD MAINTENANCE PANEL - *Ref. 8*
- [x] BLUE PUMP OVRD should be BOXED WHITE ON
- [x] Both FADEC GND PWR should be BOXED WHITE ON
- [x] APU AUTO EXT should be BOXED WHITE ON and WHITE OK
- [x] Both SVCE INT OVRD and AVIONICS COMPT LT should be BOXED WHITE ON
- [x] OXYGEN TMR RESET should be BOXED WHITE ON and WHITE FAULT

**References**

![grafik](https://user-images.githubusercontent.com/39596827/101108636-45c86800-35d5-11eb-89f1-6cb8bcfc4fb6.png)
![grafik](https://user-images.githubusercontent.com/39596827/101108826-aa83c280-35d5-11eb-9ddf-fcecb6ad3c26.png)
*Ref. 1 ATC MSG on glareshield*
![image](https://user-images.githubusercontent.com/18389085/94507681-35c48e80-0208-11eb-9f87-91b7332c819f.png)
*Ref. 2 Engine Control Panel (Below THROTTLE)*
![image](https://user-images.githubusercontent.com/18389085/94509288-d0729c80-020b-11eb-9559-6174874d5f03.png)
*Ref. 3 Image of Pedestal showing GRAVITY GEAR isn't an EMISSIVE*
![image](https://user-images.githubusercontent.com/18389085/94509347-f1d38880-020b-11eb-9002-edf3fa10bffd.png)
*Ref. 5 Image of SIDE STICK PRIORITY*
![P1010761](https://user-images.githubusercontent.com/39596827/96653688-ef131180-1339-11eb-8925-831514423c09.JPG)
*Ref. 6 Image of OVHD Panel (Zoom in for more detail, Source: komp)*
![image](https://user-images.githubusercontent.com/3533988/95403970-6035dc00-08d9-11eb-9cc2-2d052e6fbc3e.png)
*Ref. 7 Image of SAI*
![IMG_20201013_013135](https://user-images.githubusercontent.com/39596827/95859512-04e36e00-0d5f-11eb-8dd7-175c748f9877.jpg)
*Ref. 8 Image of Overhead Maintenance Panel - Source: Party Grunt on discord*
![grafik](https://user-images.githubusercontent.com/39596827/97561890-1bd1c380-19e1-11eb-97d8-e0fa00ee19ae.png)
*Ref. 9 Schematic of ADIRS*

## Closing Notes
If you need anymore references please reach out to me via this ISSUE or via DISCORD.

Discord username (if different from GitHub): Sabes#8668

**Comment by NinjaLabs-Dev** [comment]
I might have a go at this. I'll keep you update 😄

**Comment by Illuminati270** [comment]
Another one to add:

Auto Land light is backwards! The light is supposed to be full red with black words.

**Comment by davidwalschots** [comment]
Closing this, remaining items go to:

RST, CHR, DATE, GPS/INT, RUN/STP/RST shouldn't light up: #5142
XFEED should be GREEN OPEN: #5100
Auto Land light is backwards: #5100
