### ISSUE TITLE
[META] MSFS 1.9.3 (Update 3)

### ISSUE THREAD

**Issue by AdenFlorian** [flybywiresim/a32nx#964]
**The Big Diff**
https://github.com/flybywiresim/a32nx/compare/asobo-1.8.3...asobo-1.9.3

**The Plan:**
- [x] Fix any broken file references (should just be in the HTML files)
- [x] Test
- [x] Port over changes to our files
- [x] Test
- [x] Fix
  - [x] [BUG] Route not visible on ND #976 
- [x] Release v0.3.1

Workarounds/hacks that we have in place to fix things from the previous patch will be removed for 0.4.0

**Asobo files that changed that we have in our repo on master:**
- [x] asobo-aircraft-a320-neo/SimObjects/AirPlanes/Asobo_A320_NEO/engines.cfg
- [x] asobo-aircraft-a320-neo/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
- [x] asobo-aircraft-a320-neo/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO.xml
- [x] asobo-aircraft-a320-neo/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
- [x] asobo-aircraft-a320-neo/SimObjects/AirPlanes/Asobo_A320_NEO/sound/sound.xml
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/ATC/A320_Neo_ATC.html
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.html
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BRK/A320_Neo_BRK.html
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.css
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.html
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.html
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FDW/A320_Neo_FDW.html
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.css
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.html
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/RTPI/A320_Neo_RTPI.html
- [x] asobo-vcockpits-instruments-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.html
- [x] asobo-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/BaseNDCompass.js
- [x] asobo-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/PFD/AirspeedIndicator.js
- [x] asobo-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/PFD/AltimeterIndicator.js
- [x] asobo-vcockpits-instruments-airliners/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/PFD/AttitudeIndicator.js
- [x] asobo-vcockpits-instruments-navsystems/html_ui/Pages/VCockpit/Instruments/NavSystems/Shared/NavSystem.js
- [x] asobo-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/FlightElements/FlightPlanManager.js
- [x] asobo-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/MapInstrument.css
- [x] asobo-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/MapInstrument.html
- [x] asobo-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/Map/MapInstrument.js
- [x] fs-base-aircraft-common/ModelBehaviorDefs/Airliner/Airbus.xml
- [x] fs-base-aircraft-common/ModelBehaviorDefs/Airliner/FMC.xml
- [x] fs-base-aircraft-common/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml
- [x] fs-base-aircraft-common/ModelBehaviorDefs/Asobo/Airliner/AirlinerCommon.xml
- [x] fs-base-aircraft-common/ModelBehaviorDefs/Asobo/Airliner/FMC.xml
- [x] fs-base-aircraft-common/ModelBehaviorDefs/Asobo/Common/Handling.xml
- [x] fs-base-aircraft-common/ModelBehaviorDefs/Asobo/Common/Subtemplates/Deice_Subtemplates.xml
- [x] fs-base-aircraft-common/ModelBehaviorDefs/Asobo/Common/Subtemplates/Electrical_Subtemplates.xml
- [x] fs-base-aircraft-common/ModelBehaviorDefs/Asobo/Common/Subtemplates/Fuel_Subtemplates.xml

All of these files need to be checked against master, and have asobo's changes ported to our code.
Be careful to not override changes in our mod.
Read our code before pasting asobo code over it.
Conflicts will just have to be case by case, take the better code basically.

Asobo also moved some of their files around, so any of our HTMLs that reference those moved files need to update their references. These should naturally be fixed when comparing our files with their changed files.

Here is a list of all the files that changed in the handful of asobo packages that we were tracking in the asobo branch:
https://pastebin.com/6uXjx0n6

There are more changed files in other packages that we were not tracking, so just be aware.

Here is how the porting work is being split up:
- [x] model behavior xmls, including a320neo interior and exterior, and sound.xml (@DoToAdventures )
- [x] PFD (@AdenFlorian )
- [x] cfg files (@DoToAdventures )
- [x] CDU (@DoToAdventures )
- [x] BaseNDCompass, NavSystem, MapInstrument (@tyler58546 )
- [x] FlightPlanManager (@DoToAdventures )

**Comment by DoToAdventures** [comment]
CFG done in #967
I did not touch the engines.cfg as ours includes our own fuel fix for now and is thus a workaround which will have to be tested on its own and so on and so forth.

**Comment by Venorcis** [comment]
Possibly relevant changelogs (the English is not great...):

AERODYNAMICS
- Braking power on ground has been tweaked to reflect more realistic braking distances
- Fuel consumption updating mass problem has [been] fixed for some airplanes
PLANES
- Incorrect energy formulas resulting in inaccurate autopilot behavior have been fixed
- Autopilot overshooting altitude capture during descent has been fixed
- Allow up to 8500fpm max climb speed after the new AP is now more accurately respecting 6000fpm
A320neo
- Fixed issues related to copilot AP button lights
- Fix APU Fuel Flow shutting down left engine
- Fixed max thrust display
- Fixed missing runway in the MCDU perf page
- Improved disappearance of legs too early when following a flight plan
- STARs are filtered to display the ones connected to the selected runway in the MCDU
- “Invalid entry” has been replaced by “Not allowed” message in MCDU
- Flaps “F” indication replaced by “FULL” when flaps completely deployed

'PFDs shutdown randomly' is listed as a known issue (so the ground AI bug is still in it seems sadly...)

**Comment by mixMugz** [comment]
Guys. One hope is only for you. You are really great!

**Comment by AdenFlorian** [comment]
we're done porting changes over, things mostly work, there is a problem now where your route does not show up on the ND, creating an issue for that now

**Comment by AdenFlorian** [comment]
all done! v0.3.1 is released! Thanks everyone for your help!
